[package]

name = "radix_trie"
version = "0.0.4"
description = "Generic radix trie data-structure."

license = "MIT"
authors = ["Michael Sproul <micsproul@gmail.com>"]

repository = "https://github.com/michaelsproul/rust_radix_trie"
documentation = "https://michaelsproul.github.io/rust_radix_trie/"

keywords = ["trie", "patricia", "collection", "generic", "prefix"]

[dependencies]

nibble_vec = "*"
